carts/urls.py
from django.conf.urls import url
from .views import *


app_name = "carts"

urlpatterns = [

    url(r'^$', cart_home ,name='home'),
    url(r'^checkout/$', checkout_home ,name='checkout'),   
    url(r'^update/$', cart_update ,name='update'),

]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


from .views import HomeView



urlpatterns = [

    url(r'^$', HomeView.as_view(),name='home' ),

    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^cart/', include('carts.urls')),

    url(r'^', include('accounts.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.conf import settings

from django.db.models.signals import pre_save, post_save, m2m_changed
from product.models import Product

# Create your models here.

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True  
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user      = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)  # SET_NULL: (/ or models.CASCADE) Set the reference to NULL (requires the field to be nullable). For instance, when you delete a User, you might want to keep the comments he posted on blog posts, but say it was posted by an anonymous (or deleted) user. SQL equivalent: SET NULL. # CASCADE: When the referenced object is deleted, also delete the objects that have references to it (when you remove a blog post for instance, you might want to delete comments as well). SQL equivalent: CASCADE.
    products  = models.ManyToManyField(Product, blank=True)
    subtotal  = models.PositiveIntegerField(default=0)  
    total     = models.PositiveIntegerField(default=0) 
    updated   = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects   = CartManager() 

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.selling_price
        if instance.subtotal !=total: 
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)
 

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal 
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect

from orders.models import Order
from product.models import Product
from .models import Cart

# Create your views here.


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    
    return render(request, 'carts/home.html', {'cart':cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print('Show message to user, product nai!')
            return redirect('carts:home')
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()

    return redirect('carts:home')


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect('carts:home')
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    return render(request, 'carts/checkout.html', {'object':order_obj})

carts/templates/carts/checkout.html
{% extends 'base.html' %}


{% block content %}

<div class="container mb-4 mt-4">
<h1>Checkout</h1>

<p>Cart Total: {{ object.cart.total }}</p>
<p>Shipping Total: {{ object.shipping_total }}</p>
<p>Order Total: {{ object.total }}</p>

</div>
{% endblock %}

carts/templates/carts/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}

<div class="container mt-4 mb-4">
{% if cart.products.exists %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col"></th>
        <th scope="col">Product Name </th>
        <th scope="col">Product Price</th>
        <th scope="col">Remove</th>

      </tr>
    </thead>
    <tbody>
      {% for product in cart.products.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ product.title }}</td>
        <td>{{ product.selling_price }}</td>
        <td>
          {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
        </td>

      </tr>
      {% endfor %}
      <tr>
        <td colspan="2"></td>
        <td><b>Subtotal = </b>{{ cart.subtotal }}</td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td><b>Total = </b>{{ cart.total }}</td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td><a class="btn btn-lg btn-success" href="{% url 'carts:checkout' %}">Checkout</a></td>
      </tr>
    </tbody>
  </table>
  
  

{% else %}
<p class="lead">Cart is empty</p>
{% endif %}

</div>

{% endblock %}