carts/urls.py
from django.conf.urls import url
from .views import *


app_name = "carts"

urlpatterns = [

    url(r'^$', cart_home ,name='home'),
    url(r'^checkout/$', checkout_home ,name='checkout'),   
    url(r'^update/$', cart_update ,name='update'),

]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


from .views import HomeView



urlpatterns = [

    url(r'^$', HomeView.as_view(),name='home' ),

    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^cart/', include('carts.urls')),

    url(r'^', include('accounts.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import url
from .views import *


app_name = "product"

urlpatterns = [

    # url(r'^$', HomeView.as_view(),name='home'),
    url(r'^$', ProductListView.as_view(),name='products'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(),name='productsdetail'),
    # url(r'^featured/$', ProductFeaturedListView.as_view(),name='featured'),
    # url(r'^featured/(?P<slug>[\w-]+)/$', ProductFeaturedDetailView.as_view(),name='featureddetail'),

]

search/urls.py
from django.conf.urls import url
from .views import *



app_name = "search"


urlpatterns = [

    url(r'^$', SearchProductView.as_view(),name='query'),
    # url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(),name='productsdetail'),
   
]

search/views.py
from django.shortcuts import render
from product.models import Product
from django.views.generic import ListView

# Create your views here.


class SearchProductView(ListView):
    template_name = "search/view.html"
    context_object_name = "allproducts"
  
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None) # method_dict['q]
        if query is not None:
            return Product.objects.search(query)
        return Product.objects.featured()
     
            
        '''
        __icontains = field contains this
        __iexact = fields is exactly this
        '''

    

search/templates/search/view.html
{% extends 'base.html' %}

{% block title %}
Products
{% endblock %}

{% block content %}


<div class="container mt-4 mb-3">
            
        {% if query %}
        <div class=" mb-3">
         <h5>Search Results for <b>{{ query }}  </b> </h5> 
        <hr/>
        </div>
        {% else %}
        <div class="col-12 col-md-6 mx-auto ">
            {% include 'search/snippets/search-form.html' %}   
        </div>

        {% endif %}

        <hr/>

        <h1 class="text-center "> eCommerce Shop</h1>
        <div class="row mt-3">
                {% for obj in allproducts %}  
            <div class="col-md-3 card">
                <div class="m-4">
                    <img src="{{obj.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                    <h4><a href="{% url 'product:productsdetail' obj.slug %}">{{obj.title}}</a> </h4>
                    <p class="mt-3">Price: <strike>Tk. {{obj.marked_price}}</strike> <br/>Tk. {{obj.selling_price}}</p>
                    <a href="" class="btn btn-primary">Add To Cart</a>
                </div>
            </div>
            {% endfor %}
    </div>
</div>

{% endblock %}