accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from .views import login_page, register_page 


app_name = "accounts"

urlpatterns = [

    url(r'^login/$', login_page, name='login' ),
    url(r'^register/$', register_page, name='register' ),
    url(r'^logout/$', LogoutView.as_view(), name='logout' ),

   
]

carts/urls.py
from django.conf.urls import url
from .views import *


app_name = "carts"

urlpatterns = [

    url(r'^$', cart_home ,name='home'),
    url(r'^checkout/$', checkout_home ,name='checkout'),   
    url(r'^update/$', cart_update ,name='update'),

]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


from .views import HomeView



urlpatterns = [

    url(r'^$', HomeView.as_view(),name='home' ),

    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^cart/', include('carts.urls')),

    url(r'^', include('accounts.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import url
from .views import *


app_name = "product"

urlpatterns = [

    # url(r'^$', HomeView.as_view(),name='home'),
    url(r'^$', ProductListView.as_view(),name='products'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(),name='productsdetail'),
    # url(r'^featured/$', ProductFeaturedListView.as_view(),name='featured'),
    # url(r'^featured/(?P<slug>[\w-]+)/$', ProductFeaturedDetailView.as_view(),name='featureddetail'),

]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
   

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'product:products' %}">Logo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link text-light" href="{% url 'product:products' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'product:products' %}">Products</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Category
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="#">Contact</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'accounts:register' %}">Register</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'accounts:login' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'carts:home' %}">{{ request.session.cart_items }}<i class="fas fa-shopping-cart"></i>

              </a>
            </li>
          </ul>
          {% include 'search/snippets/search-form.html' %}
        </div>
      </nav>


      {% block content %}
      {% endblock %}


      <div class="jumbotron text-center text-light bg-dark mt-4" style="margin-bottom:0">
        <p> eCommerce Support </p>

        <p>Copyright 2021</p>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}

<div class="container mt-4 mb-4">

    <p class="text-center">Home Page </p>
    
    <h4 class="text-center">eCommerce Website </h4>


</div>

{% endblock %}